# Generated by Django 3.2.5 on 2021-07-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cheese', models.CharField(blank=True, max_length=128)),
                ('pastry', models.CharField(blank=True, max_length=128)),
                ('secret_ingredient', models.CharField(blank=True, max_length=128)),
                ('restaurant', models.ManyToManyField(to='core.Restaurants')),
            ],
        ),
    ]
